package seed

import "Postpartum_BackEnd/internal/entity"

func PsychologistSeedData() []entity.Psychologist {
	return []entity.Psychologist{
		{
			Name:         "Dr. Andy Dharmawangsa, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 15,
			PriceIDR:     200000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/andy_dharmawangsa.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Senin", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Senin", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Senin", StartTime: "20.00", EndTime: "21.00"},
				{DayOfWeek: "Kamis", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Kamis", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Reinaldo Batara, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 15,
			PriceIDR:     185000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/reinaldo_batara.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Selasa", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Selasa", StartTime: "20.00", EndTime: "21.00"},
				{DayOfWeek: "Jumat", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Jumat", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Jumat", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Eden, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 15,
			PriceIDR:     175000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/eden.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Rabu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Rabu", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Sabtu", StartTime: "17.00", EndTime: "18.00"},
				{DayOfWeek: "Sabtu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Sabtu", StartTime: "19.00", EndTime: "20.00"},
			},
		},
		{
			Name:         "Dr. Myra M.Kes, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 17,
			PriceIDR:     190000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/myra.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Senin", StartTime: "17.00", EndTime: "18.00"},
				{DayOfWeek: "Senin", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Rabu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Rabu", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Rabu", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Fitriyana Astuti, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 23,
			PriceIDR:     170000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/fitriyana_astuti.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Selasa", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Selasa", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Selasa", StartTime: "20.00", EndTime: "21.00"},
				{DayOfWeek: "Sabtu", StartTime: "19.00", EndTime: "20.00"},
			},
		},
		{
			Name:         "Dr. Ichdinavia Harsaya, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 22,
			PriceIDR:     165000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/ichdinavia_harsaya.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Rabu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Jumat", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Jumat", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Anna Amaliana, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 24,
			PriceIDR:     180000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/anna_amaliana.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Kamis", StartTime: "17.00", EndTime: "18.00"},
				{DayOfWeek: "Kamis", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Minggu", StartTime: "18.00", EndTime: "19.00"},
			},
		},
		{
			Name:         "Dr. Andrew Handi, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 16,
			PriceIDR:     150000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/andrew_handi.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Senin", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Senin", StartTime: "20.00", EndTime: "21.00"},
				{DayOfWeek: "Jumat", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Bayu Ariatama, M.Ked., Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 14,
			PriceIDR:     175000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/bayu_ariatama.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Selasa", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Selasa", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Kamis", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Kamis", StartTime: "20.00", EndTime: "21.00"},
			},
		},
		{
			Name:         "Dr. Benny Ardjil, Sp.KJ",
			Title:        "Sp. Jiwa",
			Job:          "Psikolog Klinis",
			ExperienceYr: 50,
			PriceIDR:     185000,
			PhotoURL:     "https://ntterfxefoklfcsmkgmy.supabase.co/storage/v1/object/public/photos/doctors/benny_ardjil.jpg",
			Schedules: []entity.PsychologistSchedule{
				{DayOfWeek: "Sabtu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Sabtu", StartTime: "19.00", EndTime: "20.00"},
				{DayOfWeek: "Minggu", StartTime: "17.00", EndTime: "18.00"},
				{DayOfWeek: "Minggu", StartTime: "18.00", EndTime: "19.00"},
				{DayOfWeek: "Minggu", StartTime: "19.00", EndTime: "20.00"},
			},
		},
	}
}
